services:
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LIFEOS_API_TITLE=LifeOS API
      - LIFEOS_DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lifeos
    env_file:
      - ../../apps/api/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ../../apps/web/.env
    command: ["pnpm", "--filter", "web", "dev"]

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=lifeos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lifeos"]
      interval: 5s
      timeout: 5s
      retries: 10


