services:
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LIFEOS_API_TITLE=LifeOS API
    env_file:
      - ../../apps/api/.env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  web:
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ../../apps/web/.env
    command: ["pnpm", "--filter", "web", "dev"]


