"""update courses

Revision ID: 05fa1118f606
Revises: b9ca24d8ff3b
Create Date: 2025-09-14 13:07:17.603091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fa1118f606'
down_revision: Union[str, Sequence[str], None] = 'b9ca24d8ff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('credits', sa.Integer(), nullable=True))
    op.drop_column('course', 'credit_hours')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('course', sa.Column('credit_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('course', 'credits')
    # ### end Alembic commands ###
