"""update users

Revision ID: 071824ad23de
Revises: c9ada44c2295
Create Date: 2025-09-13 17:23:29.553779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import AutoString


# revision identifiers, used by Alembic.
revision: str = '071824ad23de'
down_revision: Union[str, Sequence[str], None] = 'c9ada44c2295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_id', AutoString(), nullable=False))
    op.create_index(op.f('ix_user_client_id'), 'user', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_client_id'), table_name='user')
    op.drop_column('user', 'client_id')
    # ### end Alembic commands ###
