"""empty message

Revision ID: 733a8489d743
Revises: d7ad75842d84
Create Date: 2025-09-21 22:04:24.740529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '733a8489d743'
down_revision: Union[str, Sequence[str], None] = 'd7ad75842d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_account', sa.Column('plaid_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('plaid_account', 'account_id')
    op.add_column('snaptrade_account', sa.Column('snaptrade_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_snaptrade_account_account_id'), table_name='snaptrade_account')
    op.create_index(op.f('ix_snaptrade_account_snaptrade_account_id'), 'snaptrade_account', ['snaptrade_account_id'], unique=True)
    op.drop_column('snaptrade_account', 'account_id')
    op.add_column('snaptrade_connection', sa.Column('snaptrade_connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('snaptrade_connection', 'connection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snaptrade_connection', sa.Column('connection_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('snaptrade_connection', 'snaptrade_connection_id')
    op.add_column('snaptrade_account', sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_snaptrade_account_snaptrade_account_id'), table_name='snaptrade_account')
    op.create_index(op.f('ix_snaptrade_account_account_id'), 'snaptrade_account', ['account_id'], unique=True)
    op.drop_column('snaptrade_account', 'snaptrade_account_id')
    op.add_column('plaid_account', sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plaid_account', 'plaid_account_id')
    # ### end Alembic commands ###
