"""add finances

Revision ID: a9b8bd19ec21
Revises: eed1902dc484
Create Date: 2025-09-18 11:10:27.237721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b8bd19ec21'
down_revision: Union[str, Sequence[str], None] = 'eed1902dc484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plaid_account_clerk_user_id'), table_name='plaid_account')
    op.create_index(op.f('ix_plaid_account_clerk_user_id'), 'plaid_account', ['clerk_user_id'], unique=False)
    op.drop_index(op.f('ix_plaid_item_clerk_user_id'), table_name='plaid_item')
    op.create_index(op.f('ix_plaid_item_clerk_user_id'), 'plaid_item', ['clerk_user_id'], unique=False)
    op.drop_index(op.f('ix_snaptrade_account_clerk_user_id'), table_name='snaptrade_account')
    op.create_index(op.f('ix_snaptrade_account_clerk_user_id'), 'snaptrade_account', ['clerk_user_id'], unique=False)
    op.drop_index(op.f('ix_snaptrade_connection_clerk_user_id'), table_name='snaptrade_connection')
    op.create_index(op.f('ix_snaptrade_connection_clerk_user_id'), 'snaptrade_connection', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snaptrade_connection_clerk_user_id'), table_name='snaptrade_connection')
    op.create_index(op.f('ix_snaptrade_connection_clerk_user_id'), 'snaptrade_connection', ['clerk_user_id'], unique=True)
    op.drop_index(op.f('ix_snaptrade_account_clerk_user_id'), table_name='snaptrade_account')
    op.create_index(op.f('ix_snaptrade_account_clerk_user_id'), 'snaptrade_account', ['clerk_user_id'], unique=True)
    op.drop_index(op.f('ix_plaid_item_clerk_user_id'), table_name='plaid_item')
    op.create_index(op.f('ix_plaid_item_clerk_user_id'), 'plaid_item', ['clerk_user_id'], unique=True)
    op.drop_index(op.f('ix_plaid_account_clerk_user_id'), table_name='plaid_account')
    op.create_index(op.f('ix_plaid_account_clerk_user_id'), 'plaid_account', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###
