"""empty message

Revision ID: d7ad75842d84
Revises: 5aa7acc89883
Create Date: 2025-09-21 20:51:56.170900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7ad75842d84'
down_revision: Union[str, Sequence[str], None] = '5aa7acc89883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soundcloud_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('permalink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permalink_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('playlist_count', sa.Integer(), nullable=True),
    sa.Column('private_playlists_count', sa.Integer(), nullable=True),
    sa.Column('public_favorites_count', sa.Integer(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('private_tracks_count', sa.Integer(), nullable=True),
    sa.Column('reposts_count', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soundcloud_me_clerk_user_id'), 'soundcloud_me', ['clerk_user_id'], unique=False)
    op.create_table('soundcloud_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soundcloud_token_clerk_user_id'), 'soundcloud_token', ['clerk_user_id'], unique=False)
    op.add_column('snaptrade_activity', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('snaptrade_activity', 'tyoe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snaptrade_activity', sa.Column('tyoe', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('snaptrade_activity', 'type')
    op.drop_index(op.f('ix_soundcloud_token_clerk_user_id'), table_name='soundcloud_token')
    op.drop_table('soundcloud_token')
    op.drop_index(op.f('ix_soundcloud_me_clerk_user_id'), table_name='soundcloud_me')
    op.drop_table('soundcloud_me')
    # ### end Alembic commands ###
